pipeline{
    // agent any
    agent {
        node {
            label 'AGENT-1'
        }
    }
    // Pre-Build
    environment{
        REGION = "us-east-1"
        ACC_ID = "235270182665"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 59, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
   
   // Build
    stages{
        stage('init'){
            steps{
                script{
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }   
                }
            }
        }
        stage('plan'){
            steps{
                script{
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }   
                }
            }
        }
        stage('apply'){
            steps{
                script{
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }   
                }
            }
        }
        stage('Trigger Bastion ACM ALB EKS'){
            parallel {
                stage('Trigger Bastion') { 
                    steps{
                        script{
                            build job: '20-bastion', 
                            propagate: false,   
                            wait: false         
                        }
                    }
                }
                stage('Trigger ACM ALB') { 
                    stages{
                        stage('Trigger ACM'){
                            steps{
                                script{
                                    build job: '60-acm', 
                                    propagate: false,   // if ACM fails, parent pipeline suceess
                                    wait: true      // waits for the ACM pipeline to complete then only triggerss the alb
                                }
                            }
                        }
                        stage('Trigger ALB'){
                            steps{
                                script{
                                    build job: '70-ingress-alb', 
                                    propagate: false,   
                                    wait: false 
                                }
                            }
                        }
                    }
                }
                stage('Trigger EKS') { 
                    steps{
                        script{
                            build job: '80-eks', 
                            propagate: false,   
                            wait: false         
                        }
                    }
                }
            }
        }
    }

   // Post-Build
    post { 
        always { 
            echo 'I will always say Hello pipeline!'
            deleteDir()
        }
        success { 
            echo 'Hello pipeline is success!'
        }
        failure { 
            echo 'Hello pipeline is failure!'
        }
    }
}