pipeline{
    // agent any
    agent {
        node {
            label 'AGENT-1'
        }
    }
    // Pre-Build
    environment{
        REGION = "us-east-1"
        ACC_ID = "235270182665"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 59, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
   
   // Build
    stages{
        stage('init'){
            steps{
                script{
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }   
                }
            }
        }
        stage('plan'){
            steps{
                script{
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }   
                }
            }
        }
        stage('apply'){
            steps{
                script{
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }   
                }
            }
        }
/*         stage('Trigger SG'){
            steps{
                script{
                    build job: '10-sg', 
                    propagate: false, 
                    wait: false
                }
            }
        } */
    }

   // Post-Build
    post { 
        always { 
            echo 'I will always say Hello pipeline!'
            deleteDir()
        }
        success { 
            echo 'Hello pipeline is success!'
        }
        failure { 
            echo 'Hello pipeline is failure!'
        }
    }
}